version: '3'

services:
    express:
        image: ${CONTAINER_REGISTRY-ghcr.io/sehyun-hwang}/imshow-express:${TAG:-latest}
        build:
            context: express
            secrets:
                - NODE_AUTH_TOKEN
        ports:
            - ${EXPRESS_PORT-8889}:80

    stream:
        image: ${CONTAINER_REGISTRY-ghcr.io/sehyun-hwang}/imshow-nginx:${TAG:-latest}
        build: nginx
        depends_on:
            - express
        ports:
            - ${NGINX_PORT-8888}:80

secrets:
    NODE_AUTH_TOKEN:
        environment: NODE_AUTH_TOKEN
