version: '3'

services:
    express:
        image: ${CONTAINER_REGISTRY-ghcr.io/sehyun-hwang}/imshow-express:${TAG:-latest}
        build: express
        ports:
            - 8080:8080
        #volumes:
        #    - /mnt/node/utils:/mnt/node_modules/utils
        environment:
            - PORT=8080

    stream:
        image: ${CONTAINER_REGISTRY-ghcr.io/sehyun-hwang}/imshow-nginx:${TAG:-latest}
        build: nginx
        depends_on:
            - express
        ports:
            - 8000:80
