version: '3'

services:
    express:
        build: express
        ports:
            - 8080:8080
        volumes:
            - /mnt/node/utils:/mnt/node_modules/utils
        environment:
            - PORT=8080

    stream:
        build: nginx
        depends_on:
            - express
        ports:
            - 8000:80
