# fly.toml file generated for imshow-express on 2023-04-03T00:18:54+09:00

app = "imshow-express"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "nrt"


[build]
  image = "ghcr.io/sehyun-hwang/imshow-express:fly-initial"

[env]
  NGINX_HOST = "imshow-nginx.internal"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]


  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[services.ports.http_options.response.headers]
  Access-Control-Allow-Origin = "https://sehyun-hwang.github.io"
