#https://github.com/redhat-actions/push-to-registry/blob/main/.github/workflows/ghcr-push.yaml

name: Push to GHCR
on:
  push:
    branches:
      - main

env:
    IMAGE_NAME: ptr-test
    IMAGE_TAGS: v1 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build
        shell: sh

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push containers to GHCR
        run: docker-compose push
        shell: sh
        
      - name: Echo outputs
        run: |
          echo "${{ toJSON(steps.push.outputs) }}"