name: Push to GHCR
on:
  push:
    branches-ignore:
      - wip/*

  pull_request_target:
    types: [closed]

env:
  TAG: ${{ github.head_ref || github.ref_name }}

jobs:
  push-ghcr:
    name: Build and push image to GHCR
    runs-on: ubuntu-latest
    if: !github.event.pull_request_target || github.event.pull_request_target.merged

    steps:
      - name: Echo inputs
        run: env; echo $TAG
        shell: sh

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build containers
        run: docker-compose build
        shell: sh

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push containers to GHCR
        run: docker-compose push
        shell: sh